compiler:
    evm_version: null
    solc:
        version: null
        optimizer:
            enabled: true
            runs: 200
        remappings:
        - "@openzeppelin=./node_modules/@openzeppelin/"